- name: create config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'temp/s-job.xml') }}"
    name: test
    url: http://172.31.44.230:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - frontend
    - cart
    - catalogue

