- name: create Folder config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://172.31.44.230:8080
    user: admin
    password: "{{jenkins_password}}"

- name: create config file
  ansible.builtin.template:
    src: {{"TEMPLATE"}}
    dest: /tmp/s-job.xml

- name: create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.44.230:8080
    user: admin
    password: "{{jenkins_password}}"


